receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name, deployment.environment

exporters:
  # TODO: replace with your observability server IP
  otlp/tempo:
    endpoint: <OBSERVABILITY_SERVER_IP>:4317
    tls:
      insecure: true

  # TODO: replace with your observability server IP
  loki:
    endpoint: http://<OBSERVABILITY_SERVER_IP>:3100/loki/api/v1/push

  # TODO: replace with your observability server IP
  prometheusremotewrite:
    endpoint: http://<OBSERVABILITY_SERVER_IP>:9090/api/v1/write

  logging:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [loki]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
